#!/usr/bin/env python3
"""Dependency-free static build for GitHub Pages and a future custom domain."""
import argparse
import html
import json
from pathlib import Path
import shutil
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'content/site.json').read_text())
CONFIG = json.loads((ROOT / 'deployment.json').read_text())
IMAGE_SIZES = json.loads((ROOT / 'content/image-sizes.json').read_text())
parser = argparse.ArgumentParser()
parser.add_argument('--url', default=CONFIG['url'])
parser.add_argument('--custom-domain', default=CONFIG['custom_domain'])
parser.add_argument('--out', default='dist')
args = parser.parse_args()
url = args.url.rstrip('/') + '/'
parts = urlsplit(url)
if parts.scheme not in ('http', 'https') or not parts.netloc:
    raise SystemExit('--url must be an absolute HTTP(S) URL')
# On github.io, the first path component is the repository prefix, not an artifact directory.
segments = [s for s in parts.path.split('/') if s]
if parts.hostname.endswith('.github.io') and segments:
    segments = segments[1:]
if any(s in ('.', '..') for s in segments):
    raise SystemExit('Invalid site path')
out = ROOT / args.out
if out.resolve() == ROOT or ROOT not in out.resolve().parents:
    raise SystemExit('Output must be a child directory')
if out.exists():
    shutil.rmtree(out)
site = out.joinpath(*segments)
site.mkdir(parents=True)
shutil.copytree(ROOT / 'assets', site / 'assets')
e = html.escape

def page(lang):
    zh = lang == 'zh'
    def t(en, cn): return cn if zh else en
    asset = '../assets/' if zh else 'assets/'
    page_url = url + ('zh/' if zh else '')
    paper = asset + 'paper/teach-and-grow.pdf'
    def figure(num, alt, caption, cls=''):
        width, height = IMAGE_SIZES[f'fig{num}']
        return f'''<figure class="paper-figure {cls}"><a class="zoom" href="{asset}figures/fig{num}.webp" aria-label="{t('Enlarge figure: ', '放大图片：')}{e(alt)}"><img src="{asset}figures/fig{num}.webp" alt="{e(alt)}" width="{width}" height="{height}" loading="lazy" decoding="async"><span class="zoom-label">↗ {t('Enlarge', '放大')}</span></a><figcaption>{caption}</figcaption></figure>'''
    def table(key):
        d = DATA[key]
        names = {'Spatial':'空间','Object':'物体','Goal':'目标','Long':'长程','Mean':'均值','Camera':'相机','Robot':'机器人状态','Language':'语言','Light':'光照','Background':'背景','Noise':'噪声','Layout':'布局'}
        cols = ''.join(f'<th scope="col">{names.get(c,c) if zh else c}</th>' for c in d['columns'])
        maxima = [max(r[j] for r in d['rows']) for j in range(1, len(d['columns'])+1)]
        rows = ''
        for r in d['rows']:
            ours = r[0].startswith('TGL')
            cells = ''.join(f'<td>{"<strong>" if v == maxima[i] else ""}{v:.1f}{"</strong>" if v == maxima[i] else ""}</td>' for i,v in enumerate(r[1:]))
            rows += f'<tr class="{"ours" if ours else ""}"><th scope="row">{e(r[0])}</th>{cells}</tr>'
        return f'<div class="table-scroll" tabindex="0" role="region" aria-label="{key} {t("results; scroll horizontally", "结果；可横向滚动")}"><table><caption>{t("Success rate (%)", "成功率（%）")}</caption><thead><tr><th scope="col">{t("Method", "方法")}</th>{cols}</tr></thead><tbody>{rows}</tbody></table></div>'
    videos = ''
    for i,v in enumerate(DATA['videos']):
        vi = int(zh)
        pair = ''
        for role in ('teacher','system'):
            name = v['id'] + '_' + role
            label = t('Teacher demonstration','教师演示') if role == 'teacher' else t('Teach and Grow · ours','Teach and Grow · 我们的方法')
            pair += f'''<div class="video-pane {role}"><div class="video-label"><span class="status-dot"></span>{label}</div><video controls playsinline muted preload="none" poster="{asset}posters/{name}.webp" aria-label="{e(v['task'][vi])} — {label}"><source src="{asset}videos/{name}.mp4" type="video/mp4">{t('Your browser does not support embedded video.', '你的浏览器不支持内嵌视频。')} <a href="{asset}videos/{name}.mp4">MP4</a></video></div>'''
        videos += f'''<article class="demo-card" data-suite="{v['suite']}" id="demo-{i+1}"><div class="demo-heading"><div><p class="eyebrow">{v['suite'].upper()} <span>/{i+1:02d}</span></p><h3>{v['title'][vi]}</h3><p class="task-name">{v['task'][vi]}</p></div><span class="tag">{v['tag'][vi]}</span></div><div class="video-pair">{pair}</div><div class="pair-controls" hidden><button class="pair-play" type="button">▶ {t('Play both','同时播放')}</button><button class="pair-restart" type="button">↺ {t('Restart','重新播放')}</button><label>{t('Speed','速度')} <select class="pair-speed" aria-label="{t('Playback speed','播放速度')}"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label></div><p>{v['description'][vi]}</p><p class="watch-note"><strong>{t('Watch for:','观察重点：')}</strong> {v['watch'][vi]}</p><p class="play-status" role="status"></p></article>'''
    bib = f'''@techreport{{nie2026teachandgrow,
  title = {{{DATA['title']}}},
  author = {{Nie, Chang and Liu, Zhe and Wang, Hesheng}},
  institution = {{Shanghai Jiao Tong University}},
  year = {{2026}},
  url = {{{url}}}
}}'''
    nav = [("overview",t('Overview','概述')),("method",t('Method','方法')),("demos",t('Videos','视频')),("results",t('Results','结果')),("resources",t('Resources','资源'))]
    nav_html = ''.join(f'<a href="#{a}">{b}</a>' for a,b in nav)
    description=t('Training-free robot learning from sparse teaching. Reusable Skill Blocks, agent-led execution, and physical feedback turn demonstrations into lasting capability.','通过少量示教学会新任务，无需微调模型。Teach and Grow 将演示转化为可复用技能，以智能体决策和物理反馈实现机器人能力积累。')
    return f'''<!doctype html>
<html lang="{t('en','zh-CN')}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Teach and Grow · {t('Training-free Robot Learning','无需训练的机器人学习')}</title>
<meta name="description" content="{description}"><meta name="theme-color" content="#155e59"><meta name="color-scheme" content="light">
<link rel="canonical" href="{page_url}"><link rel="alternate" hreflang="en" href="{url}"><link rel="alternate" hreflang="zh-CN" href="{url}zh/"><link rel="alternate" hreflang="x-default" href="{url}">
<meta property="og:type" content="article"><meta property="og:title" content="Teach and Grow"><meta property="og:description" content="{description}"><meta property="og:url" content="{page_url}"><meta property="og:image" content="{url}assets/figures/fig1.webp"><meta name="twitter:card" content="summary_large_image">
<meta name="citation_title" content="{e(DATA['title'])}"><meta name="citation_author" content="Nie, Chang"><meta name="citation_author" content="Liu, Zhe"><meta name="citation_author" content="Wang, Hesheng"><meta name="citation_publication_date" content="2026"><meta name="citation_pdf_url" content="{url}assets/paper/teach-and-grow.pdf">
<link rel="icon" href="{asset}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{asset}style.css"><script src="{asset}app.js" defer></script>
</head><body data-lang="{lang}"><a class="skip-link" href="#main">{t('Skip to content','跳至正文')}</a>
<header class="site-header"><div class="nav-wrap"><a class="brand" href="#" aria-label="Teach and Grow home"><img src="{asset}favicon.svg" width="30" height="30" alt=""><span>TGL<span class="brand-dot">.</span></span></a><nav aria-label="{t('Main navigation','主导航')}">{nav_html}</nav><a class="language" href="{'../' if zh else 'zh/'}" lang="{t('zh-CN','en')}">{t('中文','English')} <span aria-hidden="true">↗</span></a></div></header>
<main id="main">
<section class="hero container"><p class="eyebrow hero-kicker">{t('SHANGHAI JIAO TONG UNIVERSITY · ROBOT LEARNING','上海交通大学 · 机器人学习')}</p><div class="hero-mark" aria-hidden="true"><span></span><span></span><span></span><i>↗</i></div><h1><span>Teach</span> <em>and</em> <span>Grow</span></h1><p class="paper-subtitle">An Agent-Centered Architecture<br class="desktop-break"> for General Robot Learning</p><p class="authors"><a href="mailto:changniep@gmail.com">Chang Nie</a><span>·</span>Zhe Liu<span>·</span><a href="mailto:wanghesheng@sjtu.edu.cn">Hesheng Wang</a></p><p class="affiliation">{t('School of Automation and Intelligent Sensing, Shanghai Jiao Tong University','上海交通大学 自动化与感知学院')}</p><p class="hero-summary">{t('Teach a few examples. Keep the model fixed.<br>Grow a library of skills the robot can use again.','少量示教，模型权重保持不变。<br>让机器人持续积累可复用的技能。')}</p><div class="hero-links"><a class="button primary" href="{paper}" target="_blank" rel="noopener">↗ {t('Read the paper','阅读论文')}</a><a class="button" href="#demos">▷ {t('Watch demonstrations','观看演示')}</a><a class="button text-button" href="#citation">{t('Cite this work','引用论文')} ↓</a></div><div class="hero-facts"><div><strong>Training-free</strong><span>{t('No task-time gradient updates','新任务无需梯度更新')}</span></div><div><strong>99.9<span>%</span></strong><span>{t('LIBERO · 4-suite mean','LIBERO · 4 个套件均值')}</span></div><div><strong>92.4<span>%</span></strong><span>{t('LIBERO-Plus · 7-category mean','LIBERO-Plus · 7 类扰动均值')}</span></div></div><p class="metric-note">{t('Success rates reported in the paper; settings are weighted equally.','成功率来自论文，各设置等权平均。')} <a href="#results">{t('Explore results','查看结果')} ↗</a></p></section>
<section id="overview" class="section container"><div class="section-intro"><p class="eyebrow">01 / {t('THE IDEA','核心思路')}</p><h2>{t('New skills, without a new training cycle.','学习新技能，无需重新训练模型。')}</h2><p class="lead">{t('What if teaching a robot a new task could update what it knows how to do, while its pretrained models stay fixed?','当预训练模型的权重保持不变时，机器人能否通过示教学会新的任务？')}</p></div><div class="overview-grid"><div class="prose"><p>{t('Vision-language-action and world-action models often acquire new behavior through robot data collection and policy optimization. Teach-and-Grow Learning (TGL) takes sparse successful demonstrations as a starting point for explicit skill acquisition.','视觉–语言–动作模型和世界–动作模型往往通过采集机器人数据、优化策略来获得新行为。Teach-and-Grow Learning（TGL）从少量成功演示出发，直接构建显式技能。')}</p><p>{t('The agent extracts shared subgoals, represents them as executable Skill Blocks, and grounds each block in the current scene. After the robot acts, physical feedback determines whether to continue, observe again, or repair the plan.','智能体提取演示中的共同子目标，将其表示为可执行的 Skill Blocks，并根据当前场景确定每个技能的具体执行方式。机器人动作后的物理反馈决定下一步是继续、重新观察，还是修改计划。')}</p><p>{t('Validated behavior enters the Skill Library. Experience Memory records the conditions, outcomes, and repairs that help the agent make its next decision. Task acquisition changes these explicit stores without fine-tuning the pretrained models.','通过验证的行为进入技能库。经验记忆记录条件、结果与修复方式，为下一次决策提供依据。新任务的学习更新这些显式记录，无需微调预训练模型。')}</p><p class="principle"><span lang="zh-CN">教学相长</span><br>{t('Teaching and learning promote one another.','示教给出起点，执行发现缺口，经验引导下一次学习。')}</p></div>{figure(1,t('Policy-training route and the Teach-and-Grow route to skill acquisition','策略训练与 Teach-and-Grow 技能获取流程对比'),t('From sparse teaching to reusable, verified behavior. Conceptual illustration from the paper.','从少量示教到可复用、经过验证的行为。图示来自论文。'))}</div>
<div class="contributions"><article><span>01</span><h3>{t('Sparse teaching','少量示教')}</h3><p>{t('Successful examples reveal the subgoals and their order.','成功演示揭示任务的子目标及其顺序。')}</p></article><article><span>02</span><h3>Skill Blocks</h3><p>{t('Closed-loop skills bind a reusable strategy to the current scene.','闭环技能将可复用策略落实到当前场景。')}</p></article><article><span>03</span><h3>{t('Persistent experience','持久经验')}</h3><p>{t('Skills and execution experience accumulate in separate stores.','技能与执行经验分别保存在技能库和经验记忆中。')}</p></article><article><span>04</span><h3>{t('Capability growth','能力积累')}</h3><p>{t('A scaling hypothesis connects reusable experience to future teaching demand.','以可复用经验连接未来任务误差与示教需求的缩放假设。')}</p></article></div></section>
<section id="method" class="section soft"><div class="container"><div class="section-intro"><p class="eyebrow">02 / {t('THE METHOD','方法')}</p><h2>{t('Teach. Act. Verify. Grow.','示教、执行、验证、积累。')}</h2><p class="lead">{t('The agent chooses what to do. Robot tools carry it out. The physical result decides what happens next.','智能体决定做什么，机器人工具负责执行，物理结果决定接下来怎么做。')}</p></div>{figure(2,t('Teach-and-Grow architecture: teaching, agent-led execution, and persistent growth','Teach-and-Grow 架构：示教、智能体主导执行与能力积累'),t('Teaching provides shared state changes. The agent composes and checks Skill Blocks. Verified skills and execution experience return to the next task.','示教提供共同的状态变化。智能体组合技能并检查效果，经过验证的技能与执行经验用于后续任务。'))}<div class="method-steps"><article><span class="step-num">1</span><h3>{t('Learn a meaningful change','学习有意义的状态变化')}</h3><p>{t('Find shared subgoals across demonstrations. Form candidate skills with a defined scope, an executor, and an observable success test.','提取多次演示中的共同子目标。候选技能包含明确的适用范围、执行器和可观察的成功判据。')}</p></article><article><span class="step-num">2</span><h3>{t('Compose and check','组合与检查')}</h3><p>{t('Retrieve relevant skills, ground objects and geometry in the current observation, then execute one stage and review its effect.','检索相关技能，根据当前观察确定物体与几何关系，执行一个阶段后检查其效果。')}</p></article><article><span class="step-num">3</span><h3>{t('Keep what can be reused','保留可复用的能力')}</h3><p>{t('Admit validated skills to the library. Record successful conditions, failed attempts, and repairs in Experience Memory.','将通过验证的技能纳入技能库，在经验记忆中记录成功条件、失败尝试与修复方法。')}</p></article></div><div class="block-detail"><div><p class="eyebrow">{t('THE REUSABLE UNIT','可复用的基本单元')}</p><h3>{t('Inside a Skill Block','Skill Block 的内部结构')}</h3><p>{t('A block carries a goal, an applicability scope, a strategy, a grounding function, executors, a success test, and recovery. Its semantic role stays stable; its physical realization is computed from what the robot observes now.','每个技能块包含目标、适用范围、策略、场景落地函数、执行器、成功判据与恢复机制。语义角色保持稳定，物理实现则根据机器人此刻的观察确定。')}</p><p class="small">{t('The paper’s instantiation uses OpenAI GPT-6 Astra for multimodal reasoning and Codex as the interface to robot tools.','论文中的具体实现使用 OpenAI GPT-6 Astra 进行多模态推理，通过 Codex 调用机器人工具。')}</p></div>{figure(3,t('The Skill Block contract and closed-loop execution','Skill Block 契约与闭环执行'),t('Observe → ground → execute → verify.','观察 → 场景落地 → 执行 → 验证。'))}</div></div></section>
<section id="demos" class="section container"><div class="section-intro"><p class="eyebrow">03 / {t('SEE IT IN ACTION','演示视频')}</p><h2>{t('Learn the task. Adapt the execution.','理解任务，灵活执行。')}</h2><p class="lead">{t('Five paired LIBERO demonstrations show the teacher’s example alongside Teach and Grow. Look for changes in grasping, scene grounding, and recovery.','五组 LIBERO 视频并排展示教师演示与 Teach and Grow 的执行，呈现抓取适应、场景落地与反馈纠错。')}</p></div><div class="demo-toolbar"><div class="filters" role="group" aria-label="{t('Filter demonstrations','筛选演示')}" hidden><button class="active" data-filter="All" aria-pressed="true">{t('All five','全部五组')}</button><button data-filter="Object" aria-pressed="false">Object</button><button data-filter="Spatial" aria-pressed="false">Spatial</button><button data-filter="Goal" aria-pressed="false">Goal</button></div><span class="small">{t('Teacher ← → TGL · videos play on request','左：教师 · 右：TGL · 点击播放')}</span></div><p class="small demo-note">{t('Qualitative simulation examples. Clips have different durations; joint playback starts them together without aligning individual actions. Playback speed refers to the supplied videos, not measured robot latency.','这些是仿真中的定性示例。视频时长不同，同时播放只统一起点，不对齐具体动作；播放倍速针对原视频，不代表实测机器人延迟。')}</p><div class="demo-grid">{videos}</div></section>
<section id="results" class="section soft"><div class="container"><div class="section-intro"><p class="eyebrow">04 / {t('EVALUATION','实验结果')}</p><h2>{t('From demonstrations to measurable capability.','从演示到可测量的能力。')}</h2><p class="lead">{t('The paper reports 99.9% mean success on LIBERO and 92.4% on LIBERO-Plus with fixed pretrained weights.','论文报告：在预训练权重固定的条件下，LIBERO 平均成功率为 99.9%，LIBERO-Plus 为 92.4%。')}</p></div><div class="result-tabs" role="group" aria-label="{t('Choose benchmark','选择基准')}" hidden><button class="active" data-result="libero" aria-pressed="true">LIBERO <span>99.9%</span></button><button data-result="plus" aria-pressed="false">LIBERO-Plus <span>92.4%</span></button></div><div class="result-panel" id="result-libero"><h3>LIBERO</h3><p>{t('Four suites test spatial relations, object identity, goal conditions, and longer task sequences.','四个套件分别测试空间关系、物体类别、目标条件与较长任务序列。')}</p>{table('libero')}</div><div class="result-panel" id="result-plus"><h3>LIBERO-Plus</h3><p>{t('Seven perturbation categories test changes in cameras, robot state, language, lighting, backgrounds, sensor noise, and layout.','七类扰动测试相机、机器人状态、语言、光照、背景、传感器噪声与布局变化。')}</p>{table('plus')}</div><p class="table-note">{t('Values reproduce the paper’s Tables I–II. Means weight the displayed suites or categories equally. Bold marks column maxima, including ties. TGL values are author-reported; baseline values come from the cited studies in the paper.','数值对应论文表 I–II，各套件或扰动类别等权平均；粗体表示各列最高值（含并列）。TGL 数值由作者报告，其他方法数值来自论文引用的研究。')} <a href="{paper}#page=4">{t('Methods and references in the paper','查看论文中的方法与参考文献')} ↗</a></p><div class="study-grid"><article><p class="eyebrow">{t('SKILL PERSISTENCE','技能持久化')}</p><strong>3/3 → 3/3</strong><h3>{t('Before and after reload','保存与重载前后')}</h3><p>{t('Two learned blocks solve three evaluation states and retain that result after save-and-reload in the task-specific study.','在单任务研究中，两个学得的技能块成功完成三个评估状态，保存并重载后仍为 3/3。')}</p></article><article><p class="eyebrow">{t('RELATED-TASK PILOT','相关任务试验')}</p><strong>0/6 → 4/6</strong><h3>{t('A larger reusable library','扩充可复用技能库')}</h3><p>{t('Growing the library from six to eight blocks changes success in a two-task pilot with a fixed executor.','在执行器固定的双任务试验中，技能库从六个技能块扩充至八个后，成功次数由 0/6 变为 4/6。')}</p></article><article><p class="eyebrow">{t('RUNTIME FEEDBACK','执行反馈')}</p><strong>{t('Replan & reobserve','重规划 · 再观察')}</strong><h3>{t('Outcomes change the next action','结果改变下一步动作')}</h3><p>{t('Two representative successful traces show the agent revising its remaining plan or gathering another observation after physical feedback.','两条代表性成功轨迹展示智能体如何根据物理反馈修改剩余计划或再次观察。')}</p></article></div></div></section>
<section class="section container" id="growth"><div class="section-intro"><p class="eyebrow">05 / {t('LOOKING AHEAD','研究展望')}</p><h2>{t('Experience becomes a resource that can grow.','让可复用经验成为持续积累的资源。')}</h2><p class="lead">{t('TGL asks how future-task error and teaching demand change as validated, reusable experience accumulates.','TGL 关注：随着经过验证、可复用的经验不断积累，未来任务误差和示教需求将如何变化？')}</p></div><div class="growth-grid">{figure(4,t('Hypothesized decline of task error and teaching demand with reusable experience','未来任务误差与示教需求随可复用经验增长而下降的假设'),t('A scaling hypothesis, illustrated schematically rather than fitted to a longitudinal experiment.','缩放假设示意图，并非纵向实验的拟合曲线。'))}<div class="prose"><h3>{t('A slow learner and a fast executor','慢速学习者与快速执行器')}</h3><p>{t('The agent acquires unfamiliar behavior, inspects outcomes, and keeps validated experience. Mature skills can be executed by specialized policies, planners, or controllers.','智能体获取陌生行为、检查结果并保存经过验证的经验。成熟技能可以由专用策略、规划器或控制器执行。')}</p><p>{t('The paper proposes a future distillation path in which verified trajectories train a fast policy, with uncertain cases returning to the agent. It also develops a conditional acquisition-cost model for adding skills locally.','论文提出未来可将经过验证的轨迹蒸馏到快速策略中，并将不确定的情况交回智能体处理；同时讨论局部添加技能的条件性获取成本模型。')}</p><span class="tag">{t('Hypothesis & proposed integration','理论假设与拟议集成方向')}</span></div></div><details class="deep-dive"><summary>{t('Explore the acquisition-cost model','查看能力获取成本模型')} <span>+</span></summary>{figure(5,t('Conditional acquisition-cost regimes for global updates and local Skill Blocks','全局更新与局部 Skill Block 的条件性能力获取成本对比'),t('Near-additive growth requires bounded grounding, validation, and compatibility costs. These curves describe analytic regimes.','近似可加的成本增长要求场景落地、验证与兼容性成本有界。曲线表示分析性情形。'))}</details><details class="deep-dive"><summary>{t('Explore the wider TGL ecosystem','查看完整 TGL 系统生态')} <span>+</span></summary>{figure(6,t('TGL routes knowledge, tools, learned policies, planning, and control through verification','TGL 通过验证机制连接知识、工具、学习策略、规划与控制'),t('A common semantic and verification layer connects specialized components. Dashed paths mark future distillation and fleet sharing.','统一的语义与验证层连接专用组件。虚线路径表示未来的蒸馏与多机器人共享方向。'))}</details></section>
<section id="resources" class="section resources soft"><div class="container"><div class="resource-top"><div><p class="eyebrow">06 / {t('PAPER & RESOURCES','论文与资源')}</p><h2>{t('Read the full paper.','阅读全文。')}</h2><p>{t('The technical report includes the formulation, Skill Block contract, evaluation, and extended discussion.','技术报告包含问题定义、Skill Block 契约、实验评估和扩展讨论。')}</p></div><a class="button primary" href="{paper}" target="_blank" rel="noopener">{t('Open paper · PDF','打开论文 · PDF')} ↗</a></div><div class="resource-links"><a href="#demos">{t('10 demonstration videos','10 段演示视频')} ↗</a><a href="https://github.com/biubiu3/tgl-web" target="_blank" rel="noopener">{t('Website source','网页源码')} ↗</a><a href="mailto:changniep@gmail.com">{t('Contact the authors','联系作者')} ↗</a></div><p class="small">{t('Robot implementation code is not linked in this release. The repository above contains this project website.','本次发布未提供机器人实现代码链接，上方仓库为本项目网页源码。')}</p><div class="citation" id="citation"><div><h3>BibTeX</h3><button id="copy-citation" type="button" hidden>{t('Copy citation','复制引用')}</button></div><pre><code id="bibtex">{e(bib)}</code></pre><span id="copy-status" role="status"></span></div></div></section>
</main><footer class="container"><a class="brand" href="#">TGL<span class="brand-dot">.</span></a><p>Teach and Grow · Shanghai Jiao Tong University<br><span>{t('Self-hosted images and videos. No analytics or third-party embeds.','图片与视频均由本站提供，无统计追踪或第三方嵌入。')}</span></p><a href="#">{t('Back to top','返回顶部')} ↑</a></footer><dialog id="image-dialog" aria-label="{t('Enlarged paper figure','放大的论文图片')}"><button class="dialog-close" aria-label="{t('Close image','关闭图片')}">×</button><img alt=""><p></p></dialog>
</body></html>'''

(site/'index.html').write_text(page('en'))
(site/'zh').mkdir()
(site/'zh/index.html').write_text(page('zh'))
# A project root redirects to the requested /tgl/ review route.
if site != out:
    target = '/'.join(segments) + '/'
    (out/'index.html').write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Teach and Grow</title><meta http-equiv="refresh" content="0;url={target}"><link rel="canonical" href="{url}"><p><a href="{target}">Continue to Teach and Grow →</a></p></html>')
(out/'404.html').write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found · TGL</title><style>body{{font:20px system-ui;max-width:640px;margin:15vh auto;padding:24px;color:#173d37}}a{{color:#155e59}}</style><h1>Page not found</h1><p>The page may have moved.</p><a href="{url}">Return to Teach and Grow →</a></html>')
(out/'.nojekyll').touch()
(out/'sitemap.xml').write_text(f'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>{url}</loc></url><url><loc>{url}zh/</loc></url></urlset>')
(out/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {parts.scheme}://{parts.netloc}/' + ('/'.join([s for s in parts.path.split('/') if s][:1])+'/' if parts.hostname.endswith('.github.io') and parts.path.strip('/') else '') + 'sitemap.xml\n')
if args.custom_domain:
    if '/' in args.custom_domain or args.custom_domain != parts.hostname:
        raise SystemExit('Custom domain must match the hostname in --url')
    (out/'CNAME').write_text(args.custom_domain+'\n')
print(f'Built {site.relative_to(ROOT)} → {url} (English + Chinese)')
