"""Bilingual research narrative, grounded in the current manuscript and appendices."""
def sections(t, figure, paper):
    def p(en, zh): return '<p>'+t(en,zh)+'</p>'
    def intro(n,k,title,lead):
        return f'<div class="section-intro"><p class="eyebrow">{n} / {k}</p><h2>{title}</h2><p class="lead">{lead}</p></div>'
    overview = '<section id="overview" class="section container">'+intro('01',t('THE PROBLEM','问题从哪里来'),t('Where end-to-end VLA and WAM learning becomes costly.','端到端 VLA 与 WAM 的能力扩展，难在哪里？'),t('A robot encounters a new container, a changed camera, or a grasp that no longer works. The missing behavior may be local. The effort to acquire it can reach across the entire learning system.','一个新容器、变化的相机位置，或一次不再奏效的抓取，都可能暴露局部的能力缺口。补上这个缺口，却往往牵动整个学习系统。'))
    overview += '<div class="reading-grid"><div class="article-copy">'
    overview += p('Generalist robot policies have made substantial progress by learning from large collections of observations and actions. <strong>Vision-language-action models (VLA)</strong> connect semantic understanding with control; <strong>world-action models (WAM)</strong> bring learned physical dynamics into the picture. In their end-to-end learning routes, new competence is largely absorbed into model parameters through training. These models provide valuable priors for a robot facing a new task.','通用机器人策略通过大规模观察–动作数据取得了重要进展。<strong>视觉–语言–动作模型（VLA）</strong>将语义理解与控制连接起来，<strong>世界–动作模型（WAM）</strong>进一步引入对物理动态的建模。在这类端到端学习路线中，新能力主要通过训练被吸收到模型参数里。这些模型为机器人处理新任务提供了有价值的先验。')
    overview += p('Physical interaction data, however, has a different cost structure from text or code. Much of it must be created by operating a robot or simulator: observing contact, testing a grasp, recovering from a collision risk, and checking what actually changed. Object pose, camera geometry, clutter, material, and embodiment interact. Covering one factor does not automatically cover their combinations.','但物理交互数据与文本、代码的获取成本不同。许多证据必须通过运行机器人或仿真系统才能获得：观察接触、检验抓取、应对碰撞风险，并确认实际发生了什么变化。物体姿态、相机几何、杂乱程度、材质和机器人本体又会相互影响，覆盖单个因素并不等于覆盖它们的组合。')
    overview += p('When a failure is repaired through a policy update, the process often includes new data collection, optimization, and regression checks on previously supported behavior. We call this recurring burden the <em>retraining tax</em>. It becomes particularly visible in the long tail: a rare contact condition or unusual object may require a specific lesson rather than another broad round of experience.','当系统通过更新策略来修复失败时，往往需要重新采集数据、优化模型，并回归检查原有行为。我们将这种反复出现的负担称为 <em>retraining tax</em>，即再训练负担。它在长尾场景中尤为明显：一种少见的接触条件或特殊物体，可能需要的是一条具体经验，而不是又一轮宽泛的数据积累。')
    overview += p('This exposes a second difficulty: <strong>a local failure can require a broadly coupled repair</strong>. If a VLA or WAM fails to retain an unfamiliar bowl, adding corrective data and changing its parameters does not produce a separately addressable “bowl-retention fix.” Previously supported behavior may need to be checked again. Adding a sensor or changing the gripper also introduces observation interfaces, calibration, and action compatibility to validate.','这进一步暴露出第二个困难：<strong>局部失败，可能需要牵动全局的修复</strong>。如果 VLA 或 WAM 无法夹稳一种陌生的碗，补充纠错数据、更新参数后，系统并不会自然获得一个可以单独检查和调用的“碗夹持修复模块”。原有行为可能需要重新检查；增加传感器或更换夹爪，还会引入观察接口、标定和动作兼容性的验证工作。')
    overview += p('The third difficulty is <strong>turning long-tail experience into a reusable correction</strong>. A successful trajectory may omit precisely the conditions that matter after a failed grasp. When lessons are retained only through parameter updates, the failure condition, recovery rule, and supported scope are harder to inspect or revise individually. TGL therefore asks whether a robot can preserve those objects explicitly and update the relevant behavior locally.','第三个困难是<strong>如何把长尾经验变成可以复用的纠正</strong>。成功轨迹可能恰好没有覆盖抓取失败之后最重要的条件。如果经验仅通过参数更新保留，失败条件、恢复规则与支持范围就难以被逐项检查和修改。因此，TGL 追问：能否显式保留这些对象，并局部更新相关行为？')
    overview += '</div><aside class="research-aside"><span class="mono">RESEARCH QUESTION</span><p>'+t('Can a robot acquire a new executable capability while keeping its pretrained model weights fixed?','预训练模型权重保持不变时，机器人能否获得新的可执行能力？')+'</p><div class="aside-rule"></div><span>'+t('The unit of growth: a verified, reusable behavior.','增长的基本单元：经过验证、可复用的行为。')+'</span></aside></div>'
    overview += '<div class="reading-wide">'+p('TGL studies an alternative update mechanism. A few successful demonstrations reveal an initial task structure. The robot turns that structure into explicit skills, tests them through execution, and keeps the useful behavior and its supporting experience. The pretrained stack supplies prior knowledge; the library and memory are where new task knowledge accumulates.','TGL 研究另一种更新机制：少量成功演示提供初始任务结构，机器人将其转化为显式技能，通过执行检验，再保留有用的行为及其经验依据。预训练模型提供先验，新任务知识则积累在技能库和经验记忆中。')+'</div>'
    overview += figure(1,t('Two routes to acquiring unfamiliar behavior','获取陌生行为的两种路径'),t('The paper’s conceptual comparison: policy optimization on one side, explicit skill acquisition and verification on the other.','论文中的概念对比：一侧通过策略优化获取新行为，另一侧通过显式技能构建与验证完成学习。'),'concept-figure')+'</section>'

    origins = '<section id="origins" class="section soft"><div class="container">'+intro('02',t('HOW WE ARRIVED HERE','研究思路的形成'),t('From an agent that can plan to a robot that can grow.','从会规划的 Agent，到能够积累能力的机器人。'),t('The architecture grew out of a practical question: what is still missing when a multimodal agent understands a task but cannot reliably carry it out?','这一架构源于一个具体问题：当多模态智能体理解了任务，却仍无法可靠执行时，系统究竟还缺少什么？'))
    origins += '<div class="reading-wide agent-context"><h3>'+t('From LLMs and ChatGPT to tool-using AI agents.','从 LLM、ChatGPT，到能够调用工具的 AI Agent。')+'</h3>'+p('Large language models (LLMs), made familiar through assistants such as ChatGPT and Claude, bring language understanding and reasoning into an interactive interface. Coding agents such as <a href="https://developers.openai.com/codex/" target="_blank" rel="noopener">Codex</a> and <a href="https://code.claude.com/docs/en/overview" target="_blank" rel="noopener">Claude Code</a> offer a particularly useful pattern for robotics: inspect the current state, choose a tool, act, examine the result, and revise the plan.','大语言模型（LLM）通过 ChatGPT、Claude 等助手，让语言理解与推理进入日常交互。<a href="https://developers.openai.com/codex/" target="_blank" rel="noopener">Codex</a>、<a href="https://code.claude.com/docs/en/overview" target="_blank" rel="noopener">Claude Code</a> 这类编程智能体进一步提供了一种适合借鉴到机器人领域的工作方式：检查当前状态、选择工具、执行操作、读取结果，再修改计划。')+p('TGL brings this <strong>AI-agent loop into physical manipulation</strong>. Camera observations take the place of workspace state; perception, grasping, and motion tools perform physical operations; observations and executor receipts report what happened. The agent chooses the next subgoal and tool from that evidence. Pretrained reasoning can thus organize new behavior while specialist robot components supply the physical competence.','TGL 将这种 <strong>AI Agent 的工作循环引入物理操作</strong>。相机观察对应工作区状态，感知、抓取与运动工具负责物理操作，新的观察和执行回执报告实际结果。智能体依据这些证据选择下一个子目标与工具。预训练推理由此用于组织新行为，专用机器人组件则提供物理执行能力。')+p('The paper’s concrete implementation uses <strong>OpenAI GPT-6 Astra for multimodal reasoning and Codex as the agent interface</strong>. ChatGPT and Claude illustrate the broader LLM context, and Claude Code illustrates the coding-agent pattern. This connection motivated our next question: how much of that pattern survives when a mistaken action changes the physical world?','论文的具体实现采用 <strong>OpenAI GPT-6 Astra 进行多模态推理，以 Codex 作为智能体接口</strong>。ChatGPT 与 Claude 在这里说明 LLM 的背景，Claude Code 用于说明编程智能体的工作方式。由此产生了我们的下一个问题：当一次错误操作会改变真实物理状态时，这种工作方式还需要补上哪些环节？')+'</div>'
    stages=[('01','Direct visual planning','直接从图像规划','We began by asking a multimodal agent to plan from robot-view images. It could interpret the goal, but the physical gaps remained: metric depth, collision-free motion, contact, and high-rate control. This separated semantic competence from the robot-native competence needed to make a plan executable.','最初，我们让多模态智能体直接根据机器人视角图像规划。它能够理解目标，但精确深度、无碰撞运动、接触与高频控制等问题依然存在。这一尝试让我们明确：语义层面的理解与让计划真正执行起来的机器人能力，是两个不同层次。'),('02','Tools and a return path for feedback','加入工具，并让物理反馈回到决策中','We then connected perception, grasping, planning, and control tools, returning fresh observations after short executions. The agent could revise its route when the scene disagreed with its expectation. Structured memory made a trial useful beyond the current episode by retaining its conditions, outcome, and repair.','随后，我们接入感知、抓取、规划与控制工具，并在短段执行后返回新的观察。当场景与预期不一致时，智能体可以修改路线。结构化记忆则保存尝试的条件、结果和修复方式，让一次交互的价值超出当前回合。'),('03','Sparse teaching as a productive starting point','用少量示教提供有效起点','Tool use made zero-shot agent control feasible, yet acquiring behavior through repeated trials still consumed interaction and model calls. Successful teaching supplies a useful subgoal sequence early. Exploration can then focus on the variation, correction, and missing transitions that the demonstrations do not cover. This became the Teach-and-Grow route.','工具调用使零样本智能体控制成为可能，但反复试错仍会消耗物理交互与模型调用。成功示教能够提前提供有用的子目标序列，使探索集中于演示没有覆盖的变化、纠错和缺失环节。这逐渐形成了 Teach-and-Grow 的路线。')]
    origins += '<div class="research-timeline">'
    for n,en,cn,body,bcn in stages:
        origins += f'<article><span class="timeline-index">{n}</span><div><h3>{t(en,cn)}</h3>{p(body,bcn)}</div></article>'
    origins += '</div><div class="research-note"><span lang="zh-CN">教学相长</span><p>'+t('Teaching gives exploration a starting structure. Execution exposes what the teaching left unresolved. Those gaps make the next teaching intervention more focused.','示教为探索提供初始结构，执行暴露示教尚未解决的问题，这些缺口又让下一次指导更有针对性。')+'</p></div><div class="reading-wide">'+p('Teaching reduced the search for a useful starting plan. The next question was what to keep from it: a record of one successful episode, or a behavior that could be grounded and executed in another scene?','示教缩小了寻找有效初始计划的范围。接下来的问题是，究竟要从中保留什么：一次成功回合的记录，还是能够在另一个场景中落实并执行的行为？')+'</div></div></section>'

    idea = '<section id="idea" class="section container">'+intro('03',t('THE CENTRAL IDEA','核心 IDEA'),t('Make executable capability the object of learning.','把可执行能力本身，作为学习的对象。'),t('A demonstration contains both a strategy worth keeping and physical details that belong to one scene. TGL separates them.','一次演示既包含值得保留的策略，也包含只属于某个场景的物理细节。TGL 将二者分开。'))
    idea += '<div class="reading-grid"><div class="article-copy">'
    idea += p('Consider placing a bowl on a plate. Across demonstrations, the hand may approach from different directions and follow different paths. The shared structure is more stable: acquire the requested bowl, establish that it is held, move toward the target relation, and release it onto the plate.','以“把碗放到盘子上”为例：不同演示中的接近方向、抓取位置和运动轨迹可以不同，但共同结构更稳定——获得目标碗，确认它已被夹持，朝目标放置关系移动，再将其释放到盘子上。')
    idea += p('TGL represents a meaningful change as a <strong>Skill Block</strong>. The block keeps the goal, reusable strategy, supported conditions, and outcome test. The current observation supplies the actual object pose, grasp, path, and control target. Reuse therefore preserves the intended effect while allowing the physical realization to change.','TGL 用 <strong>Skill Block</strong> 表示一次有意义的状态变化。技能块保留目标、可复用策略、支持条件和效果判据；实际的物体姿态、抓取、路径与控制目标，则来自当前观察。复用保留的是预期效果，同时允许物理实现发生变化。')
    idea += p('Training-free has a precise meaning here: acquiring the incoming task invokes no gradient update, fine-tuning, or reinforcement-learning stage. The agent and its specialist models may already be pretrained. New task knowledge changes the explicit skill and memory state.','这里的 training-free 有明确含义：获取当前新任务时，不进行梯度更新、微调或强化学习训练。智能体和专用模型可以已经完成预训练；新任务知识更新的是显式技能与记忆状态。')
    idea += '</div><div class="state-diagram"><div class="state-row"><span class="mono">θ</span><div><b>'+t('Pretrained model weights','预训练模型权重')+'</b><small>'+t('Fixed during task acquisition','任务获取过程中保持固定')+'</small></div><span class="state-label">FIXED</span></div><div class="state-row evolving"><span class="mono">B</span><div><b>Skill Library</b><small>'+t('Executable behaviors, scopes, and contracts','可执行行为、适用范围与契约')+'</small></div><span class="state-label">GROWS</span></div><div class="state-row evolving"><span class="mono">M</span><div><b>Experience Memory</b><small>'+t('Conditions, outcomes, diagnoses, and repairs','条件、结果、诊断与修复')+'</small></div><span class="state-label">GROWS</span></div><p>'+t('A task leaves the robot with something it can retrieve, inspect, and execute again.','完成任务后，机器人留下可以检索、检查和再次执行的能力。')+'</p></div></div>'
    idea += '<div class="invariant-strip"><div><span class="mono">RETAIN</span><h3>'+t('Semantic effects & strategy','语义效果与策略')+'</h3><p>'+t('What should change, in which order, under which conditions.','什么需要改变、先后顺序如何、适用于哪些条件。')+'</p></div><span class="strip-cross">×</span><div><span class="mono">RECOMPUTE</span><h3>'+t('Current physical realization','当前物理实现')+'</h3><p>'+t('Object bindings, grasp geometry, collision-free motion, and control.','物体绑定、抓取几何、无碰撞运动与具体控制。')+'</p></div></div><div class="reading-wide">'+p('That separation defines what is learned. Making it work on a robot requires a second connection: each retained subgoal must lead to an action in the current scene, and each action must return evidence that can change the next decision.','这种分离明确了学习的对象。要让它在机器人上奏效，还需要建立另一层连接：保留的子目标必须能转化为当前场景中的动作，而动作必须返回足以改变下一步决策的证据。')+'</div></section>'

    method = '<section id="method" class="section soft"><div class="container">'+intro('04',t('INSIDE THE ARCHITECTURE','架构如何工作'),t('Reason over subgoals. Close the loop in the world.','围绕子目标推理，在物理世界中闭环。'),t('The agent organizes the task at meaningful state transitions. Specialized executors handle the geometry and continuous control within each block.','智能体在有意义的状态变化处组织任务，专用执行器处理每个技能块内部的几何与连续控制。'))
    method += figure(2,t('Teaching, agentic execution, and persistent growth in TGL','TGL 的示教、智能体执行与持久积累'),t('One task moves through teaching, composition, execution, verification, and persistent storage. The resulting library and memory become the starting point for the next task.','一个任务经历示教、组合、执行、验证与持久化。形成的技能库与经验记忆成为下一个任务的起点。'))
    rows=[('A','Read demonstrations as evidence about change','把演示读成状态变化的证据','Demonstrations are divided around meaningful events such as acquiring an object or establishing a containment relation. Segments align by what they accomplish, even when their timing and motion differ. The shared structure becomes a candidate strategy; variation determines how broadly that strategy can be claimed. A single object-specific example stays narrow until additional evidence supports a broader scope.','系统围绕抓住物体、形成容纳关系等事件划分演示片段。片段按完成的效果对齐，即使时间与运动方式不同。共同结构形成候选策略，演示中的变化决定该策略能支持多大范围。单个物体上的经验不会自动成为通用技能，更宽的范围需要更多证据。'),('B','Give each skill a contract with the scene','让每个技能与当前场景建立明确契约','A block answers practical questions: what effect is intended, when does it apply, what evidence is needed, which executors can realize it, how is success observed, and what recovery is allowed? For an acquisition block, a closed gripper alone need not establish that the object is held. Verification must refer to the intended physical effect.','每个技能块回答具体问题：期望什么效果、何时适用、需要什么证据、哪些执行器能够实现、如何观察成功，以及允许什么恢复动作？例如，获取物体时，夹爪闭合并不必然意味着物体已被夹住。验证必须指向预期的物理效果。'),('C','Revise the remaining plan after the robot acts','机器人动作后，再决定剩余计划','The working plan is an ordered composition of blocks, but its remainder can change. A passed effect permits the next stage. A failed or inconclusive effect can prompt another observation, a different executor, or a revised route. This is where the agent’s reasoning meets physical feedback: what happens next depends on what actually happened.','当前计划由一组有序技能块组成，但尚未执行的部分可以改变。效果通过验证后进入下一阶段；失败或不确定的效果则可能触发再次观察、更换执行器或修改路线。智能体的推理在这里与物理反馈相接：下一步取决于真实发生的结果。'),('D','Validate before making a candidate reusable','验证通过后，候选行为才进入复用流程','A promising candidate is evaluated beyond its teaching demonstrations. Its supported scope, executor compatibility, outcome test, and recovery are checked before library admission. Weak candidates can be narrowed or repaired. This makes library growth an explicit decision about a behavior and the conditions under which it works.','有希望的候选行为需要在示教之外的场景中评估。进入技能库前，要检查支持范围、执行器兼容性、效果判据和恢复行为。不够可靠的候选可以缩小范围或修复。技能库的增长因此成为一个明确决策：保留什么行为，以及它在什么条件下有效。')]
    method += '<div class="method-narrative">'
    for n,en,cn,body,bcn in rows:
        method += f'<article><span class="mono method-letter">{n}</span><div><h3>{t(en,cn)}</h3>{p(body,bcn)}</div></article>'
    method += '</div>'+figure(3,t('Fields and runtime loop of a Skill Block','Skill Block 的字段与运行时闭环'),t('The contract connects a semantic subgoal to grounded execution and observable evidence.','技能契约连接语义子目标、落实到当前场景的执行，以及可观察的结果证据。'))
    method += '<div class="walkthrough"><div class="walkthrough-heading"><span class="eyebrow">'+t('A WORKED CONCEPTUAL EXAMPLE','一个贯穿方法的概念示例')+'</span><h3>'+t('“Put the bowl on the plate.”','“把碗放到盘子上。”')+'</h3><p>'+t('Follow which information is retained and which decisions are made again.','看看哪些信息被保留，哪些决策需要根据当前场景重新做出。')+'</p></div><div class="walk-tabs" role="group" aria-label="'+t('Explore the execution stages','查看执行阶段')+'" hidden>'
    steps=[('teach','Read the teaching','理解示教','Acquire → transport → release','获取 → 搬运 → 释放','The demonstrations supply subgoals and ordering. They also suggest conditions to check, such as retaining the bowl before starting transport. Their original pixel coordinates and exact trajectory are not the reusable strategy.','演示提供子目标与顺序，也揭示需要检查的条件，例如搬运前应保持对碗的夹持。原始像素坐标和精确轨迹不属于可复用策略。'),('ground','Ground the block','落实到当前场景','Current bowl → feasible grasp','当前目标碗 → 可行抓取','The block binds the requested object to the current observation. A compatible grasping and motion backend computes the physical action. The contact point can differ from the teacher’s while the intended acquired state remains the same.','技能块将任务中的目标物体绑定到当前观察，由兼容的抓取和运动后端计算具体动作。接触位置可以与教师不同，但希望达到的“已获得物体”状态保持一致。'),('verify','Read the outcome','读取动作结果','Effect → continue / reobserve / repair','物理效果 → 继续／再观察／修复','After execution, a verifier examines whether the bowl is actually held. A weak or failed grasp changes the next decision. The agent can look again or revise the remaining route before attempting placement.','执行后，验证器检查碗是否确实被夹持。不牢固或失败的抓取会改变下一步决策，智能体可以再次观察，或在放置前修改剩余路线。'),('retain','Keep the lesson','保留可复用经验','Validated behavior + useful context','已验证行为 + 有用的条件信息','The executable strategy and its scope belong in the Skill Library after validation. The conditions of the attempt, its outcome, and a useful repair belong in Experience Memory. A future task can retrieve both.','通过验证的可执行策略及其范围进入技能库。这次尝试的条件、结果和有用的修复方式进入经验记忆，后续任务可以同时检索两者。')]
    for i,(key,en,cn,*_) in enumerate(steps):method += f'<button data-stage="{key}" aria-pressed="{str(i==0).lower()}"><span>0{i+1}</span>{t(en,cn)}</button>'
    method += '</div>'
    for key,en,cn,state,scn,body,bcn in steps:
        method += f'<article class="walk-panel" id="stage-{key}"><span class="mono">{t(en,cn)}</span><h4>{t(state,scn)}</h4>{p(body,bcn)}</article>'
    method += '</div><p class="implementation-note">'+t('In the paper’s current system, OpenAI GPT-6 Astra and Codex provide task-level reasoning and tool interaction. Detection, segmentation, RGB-D geometry, Contact-GraspNet, MPLib, and controllers supply the physical grounding and execution.','论文当前系统使用 OpenAI GPT-6 Astra 和 Codex 进行任务级推理与工具交互。检测、分割、RGB-D 几何、Contact-GraspNet、MPLib 与控制器负责物理场景落地和执行。')+'</p></div></section>'

    memory='<section id="memory" class="section container">'+intro('05',t('WHAT THE ROBOT KEEPS','机器人究竟保留了什么'),t('A skill stores behavior. Memory stores its lessons.','技能保存行为，记忆保存使用它的经验。'),t('Solving an episode and acquiring a lasting capability are different events. TGL makes the retained objects explicit.','完成一次任务与获得持久能力，是两个不同的事件。TGL 将需要保留的对象显式化。'))
    memory+='<div class="memory-columns"><article><span class="mono">B / EXECUTABLE</span><h3>Skill Library</h3>'+p('The library holds behaviors that can be selected and run: their subgoals, supported conditions, grounding rules, compatible tools, and verification logic. A text description of “how to grasp” is not sufficient. The block must connect that intent to an executor and a test of its effect.','技能库保存能够被选择并运行的行为：子目标、支持条件、场景落地规则、兼容工具与验证逻辑。仅有一段“如何抓取”的文字描述并不够，技能块还必须将意图连接到执行器，以及对效果的检查。')+'</article><article><span class="mono">M / CONTEXTUAL</span><h3>Experience Memory</h3>'+p('Memory keeps the context of use: the task, selected blocks, observations, outcome, diagnosis, and repair. A failed attempt may reveal an unsuitable grasp family or an ambiguous observation. Keeping that explanation can guide the next selection without turning every episode into a new executable block.','经验记忆保存使用情境：任务、选用的技能块、观察、结果、诊断与修复。一次失败可能暴露不合适的抓取方式或含糊的观察。保留这些解释，可以指导下一次选择，而不必把每个回合都变成新的可执行技能。')+'</article></div><div class="reading-wide">'
    memory+=p('This separation also makes the system inspectable. A person can narrow an overgeneralized scope, change a recovery rule, or mark an executor version as incompatible. Retaining a file does not by itself guarantee retained behavior: the right block must still be retrieved, grounded with current sensing, and executed successfully. These are distinct questions for a robot that learns over time.','这种分离也使系统更容易检查。人可以收窄过度泛化的范围、修改恢复规则，或标记不兼容的执行器版本。保存了文件，并不自动保证保留了行为能力：系统仍需检索到正确技能，将其落实到当前传感信息中，并成功执行。这些是持续学习机器人需要分别回答的问题。')+'</div><div class="reading-wide">'+p('The following demonstrations make this loop concrete. Start with the teacher’s task structure, then follow how TGL realizes it through a different grasp or responds when the first attempt does not secure the object.','下面的视频把这个过程具体呈现出来：先看教师给出的任务结构，再看 TGL 如何采用不同的抓取实现它，以及第一次未能夹稳物体后如何继续尝试。')+'</div></section>'

    investigation='<section id="results" class="section soft"><div class="container">'+intro('07',t('WHAT WE INVESTIGATED','我们进行了哪些研究'),t('Test the learning mechanism, as well as the task outcome.','既考察任务结果，也检验学习机制。'),t('The videos show how the robot behaves in individual scenes. The experiments examine the mechanisms behind that behavior: where a skill comes from, what survives a task, and what changes the next execution.','视频展示机器人在具体场景中的行为。实验进一步考察这些行为背后的机制：技能从哪里来、一次任务结束后留下什么，以及什么因素改变了下一次执行。'))
    studies=[('Demonstration → semantic effects','从演示到语义效果','The visual study examines acquisition and release stages in saved demonstration images. It separates recovering the intended stage sequence from locating an exact temporal boundary. Observable effect tests then check the physical changes. This bounded study uses deterministic visual cues and typed rules to isolate the representation and verification mechanism.','视觉研究检查保存的演示图像中的获取与释放阶段，区分“恢复正确的阶段顺序”与“精确定位时间边界”，再用可观察效果检查物理变化。这项限定范围的研究使用确定性视觉线索与类型化规则，单独考察表示和验证机制。'),('Candidate → persistent Skill Block','从候选行为到持久技能','A task-specific study follows skills through induction, validation on separated states, library admission, storage, and reload. It also tests what happens beyond the learned scope. The important behavior is that execution checks the required effect before allowing the next stage.','单任务研究跟踪技能归纳、独立状态验证、入库、保存与重载的完整过程，并考察超出学得范围后的执行情况。关键行为是：系统检查必要效果，只有满足条件才允许进入下一阶段。'),('Physical feedback → a revised decision','从物理反馈到修正决策','Representative online traces inspect two choices: replan the remaining route in a bowl-placement task and gather another observation during drawer opening. A separate failure cohort localizes issues before motion, in path consistency or calibration, and at gripper closure. These attempts make the physical interfaces visible as places where the system must improve.','代表性在线轨迹考察两类决策：在碗放置任务中重规划剩余路线，在开抽屉任务中再次观察。另一组失败试验将问题定位到运动前、路径一致性或标定，以及夹爪闭合等环节。这些尝试明确了系统需要改进的物理接口。'),('Library growth → related-task reuse','从技能库扩充到相关任务复用','A controlled pilot keeps the executor and evaluation conditions fixed while adding learned acquisition and release blocks. It examines whether a change in the explicit library changes related-task execution. LIBERO and LIBERO-Plus evaluations provide a broader view of task completion and behavior under environmental perturbations.','一项受控试验固定执行器与评估条件，仅增加学得的获取和释放技能，考察显式技能库的变化能否改变相关任务的执行。LIBERO 与 LIBERO-Plus 评估则从更广的范围考察任务完成情况与环境扰动下的行为。')]
    investigation+='<div class="study-narrative">'
    for en,cn,body,bcn in studies:investigation+='<article><h3>'+t(en,cn)+'</h3>'+p(body,bcn)+'</article>'
    investigation+='</div><div class="paper-callout"><p>'+t('Experimental protocols, quantitative results, and comparison tables are available in the paper.','实验协议、定量结果和方法对比表请参阅论文。')+f'</p><a href="{paper}#page=4">'+t('Read the evaluation','阅读实验部分')+' ↗</a></div></div></section>'

    growth='<section id="growth" class="section container">'+intro('08',t('THE LARGER RESEARCH DIRECTION','更长远的研究方向'),t('Scale the experience a robot can actually reuse.','让机器人真正能够复用的经验持续增长。'),t('These studies follow the path from a taught task to a reusable skill. The next question concerns a longer timescale: what happens as that process repeats throughout a robot’s working life?','这些研究跟踪了从示教任务到可复用技能的过程。下一个问题涉及更长的时间尺度：当这个过程在机器人的整个工作周期中反复发生时，会带来什么变化？'))
    growth+='<div class="reading-wide">'+p('More stored trajectories do not necessarily mean more capability. Experience is useful only if it can still be retrieved, grounded, and composed for a new scene. The Teach-and-Grow hypothesis relates this effective reusable experience to declining future-task error and teaching demand. It is a hypothesis about lifelong capability growth, rather than a claim that the present experiments fit a universal scaling law.','存储更多轨迹并不必然带来更多能力。只有能够在新场景中被检索、落实和组合的经验，才具有复用价值。Teach-and-Grow 假设将这种有效可复用经验与未来任务误差、示教需求的下降联系起来。它讨论的是终身能力积累，而非声称当前实验已经拟合出普适缩放定律。')+'</div>'
    growth+=figure(4,t('Teach-and-Grow scaling hypothesis and future fast-policy path','Teach-and-Grow 缩放假设与未来快速策略路径'),t('Conceptual predictions: more reusable experience can reduce future error and the teaching required for related tasks. The curves are schematic.','概念性预测：可复用经验的积累，有望降低未来任务误差和相关任务的示教需求。曲线为示意。'))
    growth+='<div class="reading-wide subtopic"><h3>'+t('Acquire unfamiliar behavior deliberately; execute familiar behavior efficiently.','对陌生行为进行细致获取，让熟悉行为高效执行。')+'</h3>'+p('Agentic acquisition uses repeated observation, reasoning, and tool calls. That deliberation is useful at the frontier of the robot’s knowledge, but it is more expensive than feed-forward policy inference. The proposed slow-teacher/fast-student path assigns the agent to novelty and diagnosis, while a learned policy handles mature behavior. Verified trajectories could later train that student; distillation is a proposed extension of the current work.','智能体获取行为时需要反复观察、推理与调用工具。这种细致处理适合机器人尚不熟悉的任务，但成本高于前馈策略推理。因此，拟议的“慢教师–快学生”路线让智能体处理陌生任务与诊断，让学习策略执行成熟行为。未来可以用经过验证的轨迹训练学生策略；蒸馏是本工作的扩展方向。')+'</div>'
    growth+='<div class="reading-wide subtopic"><h3>'+t('VLA, WAM, and classical robotics remain part of the system.','VLA、WAM 与经典机器人方法都可以进入这一系统。')+'</h3>'+p('A learned policy can implement a block, execute a familiar composition, or become a future student. A geometric planner can bridge two skills; a visual servo can close a local loop; tactile sensing can strengthen a contact check. TGL supplies the semantic contract and feedback structure through which these components contribute to a task.','学习策略可以实现某个技能块、执行熟悉的技能组合，或成为未来的学生。几何规划器可以连接两个技能，视觉伺服可以完成局部闭环，触觉可以加强接触检查。TGL 提供语义契约与反馈结构，让这些组件共同服务于任务。')+p('The same perspective extends to teaching sources. Robot trajectories, simulation, human video, and written procedures offer different kinds of evidence. A manual may reveal the order of operations while leaving the grasp unresolved. The architecture preserves that distinction: semantic knowledge guides acquisition, and robot-specific grounding and validation determine what can actually run.','同样的思路也适用于示教来源。机器人轨迹、仿真、人类视频与书面操作流程提供不同类型的证据。手册可能揭示操作顺序，却没有解决抓取方式。架构保留这种区别：语义知识指导获取，机器人相关的场景落地与验证决定哪些行为真正能够运行。')+'</div>'
    growth+=figure(6,t('Models, tools, teaching sources, and feedback in the TGL ecosystem','TGL 生态中的模型、工具、示教来源与反馈'),t('A whole-system view. Dashed paths mark proposed distillation and fleet sharing.','系统整体视角。虚线路径表示拟议的蒸馏与多机器人共享。'))
    growth+='<details class="deep-dive"><summary>'+t('Why local skill updates may change acquisition cost','为什么局部技能更新可能改变能力获取成本')+' <span>+</span></summary><div class="reading-wide">'+p('A local skill addition can avoid reopening every part of the learning system, provided grounding, validation, compatibility, and retrieval remain manageable. Those conditions matter: unrestricted pairwise compatibility checks can make library growth expensive. The paper analyzes these different cost regimes rather than treating low-cost growth as automatic.','如果场景落地、验证、兼容性检查和检索成本保持可控，局部增加技能就可能避免重新更新整个学习系统。这些条件至关重要：不受限制的两两兼容性检查同样可能使技能库增长变得昂贵。论文分析不同的成本情形，而不把低成本增长视为自动成立。')+'</div>'+figure(5,t('Conditional acquisition-cost regimes','条件性的能力获取成本模型'),t('Analytic cost regimes under different assumptions about coverage and local compatibility.','在不同覆盖需求与局部兼容性假设下的分析性成本情形。'))+'</details></section>'
    return dict(overview=overview,origins=origins,idea=idea,method=method,memory=memory,investigation=investigation,growth=growth)
