"""Bilingual research narrative, grounded in the current manuscript and appendices."""
def sections(t, figure, paper, data=None):
    def p(en, zh): return '<p>'+t(en,zh)+'</p>'
    seo = (data or {}).get('seo', {})
    terms = seo.get('terms', [])
    def intro(n,k,title,lead):
        return f'<div class="section-intro"><p class="eyebrow">{n} / {k}</p><h2>{title}</h2><p class="lead">{lead}</p></div>'
    overview = '<section id="overview" class="section container">'+intro('01',t('THE PROBLEM','问题从哪里来'),t('Where end-to-end robot learning gets expensive.','端到端机器人学习的成本，卡在哪里？'),t('A robot meets a new container, a changed camera, or a grasp that no longer works. The gap may be small. Paying for it can reach across the whole learning system.','一个新容器、一次相机位置变化，或一次不再奏效的抓取，可能只是很小的能力缺口；但为它付出的代价，往往会牵动整个学习系统。'))
    overview += '<div class="reading-grid"><div class="article-copy">'
    overview += p('Generalist robot policies have advanced by learning from large collections of observations and actions. <strong>Vision-language-action models (VLA)</strong> connect semantic understanding to control; <strong>world-action models (WAM)</strong> add learned physical dynamics. Both routes put new competence into model parameters through training, and that trained prior is what a robot leans on when an unfamiliar task arrives.','通用机器人策略通过大规模观察–动作数据不断前进。<strong>视觉–语言–动作模型（VLA）</strong>把语义理解接到控制上，<strong>世界–动作模型（WAM）</strong>进一步引入学习到的物理动态。两条路线都通过训练把新能力写进模型参数；机器人面对陌生任务时，依靠的正是这份训练出来的先验。')
    overview += p('Physical interaction data has a different cost structure from text or code. Most of it exists only after a robot or simulator has been run: contact has to be observed, a grasp has to be tried, a collision risk has to be recovered from, and the actual change has to be checked. Object pose, camera geometry, clutter, material, and embodiment also interact, so covering one factor does not cover their combinations.','物理交互数据的成本结构与文本、代码不同。它们大多只有在机器人或仿真运行之后才存在：接触需要观察，抓取需要尝试，碰撞风险需要处理，变化需要确认。而物体姿态、相机几何、杂乱程度、材质与机器人本体之间又会相互影响，覆盖其中一个因素，并不等于覆盖它们的组合。')
    overview += p('Repairing a failure through a policy update usually means new data collection, another optimization run, and regression checks on everything the policy already supported. We call this recurring burden the <em>retraining tax</em>. It shows up most clearly in the long tail, where a rare contact condition or an unusual object needs one specific lesson rather than another broad round of experience.','如果通过更新策略来修复一次失败，通常要重新采集数据、再跑一轮优化，并对策略此前支持的所有行为做回归检查。我们把这种反复出现的负担称为 <em>retraining tax</em>（再训练成本）。它在长尾场景中格外明显：一种少见的接触条件、一件特殊的物体，需要的往往是一条具体经验，而不是又一轮宽泛的数据积累。')
    overview += p('The repair is also hard to keep local. If a VLA fails to retain an unfamiliar bowl, corrective data and updated parameters do not leave behind a separately addressable “bowl-retention fix”; the change spreads through the weights, and earlier behavior has to be checked again. A new sensor or gripper repeats the problem at the interface, where observation format, calibration, and action compatibility all need validation.','修复也难以局限在出问题的地方。如果 VLA 夹不稳一种陌生的碗，补充数据并更新参数之后，并不会留下一个可以单独检查和调用的“碗夹持修复模块”——改动分散在权重里，原有行为还得重新验证。换一个传感器或夹爪，同样的问题会在接口层重现：观测格式、标定与动作兼容性都需要重新验证。')
    overview += p('Long-tail experience is also hard to turn into a reusable correction. A successful trajectory may say nothing about the conditions that mattered after the failed grasp, and when the lesson lives only in parameters, the failure condition, the recovery rule, and the supported scope cannot be inspected or revised one at a time. TGL starts from that question: can a robot keep those objects explicit, and update only the behavior that is affected?','长尾经验同样难以变成可复用的纠正。一段成功轨迹，可能恰好没有记录抓取失败之后真正起作用的那些条件；当经验只存在于参数中，失败条件、恢复规则与适用范围就无法被逐项检查和修改。TGL 正是从这个疑问出发：机器人能否把这些对象显式保留下来，并且只更新受影响的那部分行为？')
    overview += '</div><aside class="research-aside"><span class="mono">RESEARCH QUESTION</span><p>'+t('Can a robot acquire a new executable capability while keeping its pretrained model weights fixed?','预训练模型权重保持不变时，机器人能否获得新的可执行能力？')+'</p><div class="aside-rule"></div><span>'+t('The unit of growth: a verified, reusable behavior.','增长的基本单元：经过验证、可复用的行为。')+'</span></aside></div>'
    overview += '<div class="reading-wide">'+p('TGL explores a different update mechanism. A few successful demonstrations give an initial task structure; the robot turns that structure into explicit skills, tests them by execution, and keeps what worked together with the experience that explains it. The pretrained stack still supplies the priors. What changes is where new task knowledge lives.','TGL 尝试的是另一种更新机制。少量成功演示给出初始任务结构，机器人把它转成显式技能，通过执行来检验，再把有效的部分连同解释它的经验一起保留下来。预训练模型仍然提供先验，改变的是新任务知识存放的位置。')+'</div>'
    overview += figure(1,t('Two routes to acquiring unfamiliar behavior','获取陌生行为的两种路径'),t('The paper’s conceptual comparison: policy optimization on one side, explicit skill acquisition and verification on the other.','论文中的概念对比：一侧通过策略优化获取新行为，另一侧通过显式技能构建与验证完成学习。'),'concept-figure')+'</section>'

    origins = '<section id="origins" class="section soft"><div class="container">'+intro('02',t('HOW WE ARRIVED HERE','研究思路的形成'),t('From an agent that can plan to a robot that can grow.','从“会规划”的智能体，到“能积累”的机器人。'),t('The architecture grew out of a practical question: what is still missing when a multimodal agent understands a task but cannot reliably carry it out?','这套架构源于一个很实际的问题：当多模态智能体理解了任务，却仍然无法可靠完成时，缺的到底是什么？'))
    origins += '<div class="reading-wide agent-context"><h3>'+t('From LLMs and ChatGPT to tool-using AI agents.','从大语言模型与 ChatGPT，到会调用工具的 AI 智能体')+'</h3>'+p('Large language models (LLMs), familiar through assistants such as ChatGPT and Claude, brought language understanding and reasoning into an interactive interface. Coding agents such as <a href="https://developers.openai.com/codex/" target="_blank" rel="noopener">Codex</a> and <a href="https://code.claude.com/docs/en/overview" target="_blank" rel="noopener">Claude Code</a> add a working pattern that transfers well to a robot: inspect the current state, choose a tool, act, look at the result, and revise the plan.','大语言模型（LLM）通过 ChatGPT、Claude 这类助手，把语言理解与推理带进了交互界面。<a href="https://developers.openai.com/codex/" target="_blank" rel="noopener">Codex</a>、<a href="https://code.claude.com/docs/en/overview" target="_blank" rel="noopener">Claude Code</a> 等编程智能体则给出了一套很适合搬到机器人上的工作方式：查看当前状态、选择工具、执行、读取结果、修正计划。')+p('TGL moves that loop into physical manipulation. Camera images stand in for workspace state, perception and grasping and motion tools carry out the operations, and new observations report what the action changed. From that evidence the agent chooses the next subgoal and the next tool. Reasoning organizes the task; specialist robot components supply the physical competence.','TGL 把这个循环搬进了物理操作。相机图像对应工作区状态，感知、抓取与运动工具负责实际操作，新的观察报告动作改变了什么。智能体依据这些信息选择下一个子目标与下一个工具——推理负责组织任务，专用机器人组件负责物理执行。')+p('The paper’s implementation uses <strong>OpenAI GPT-6 Astra for multimodal reasoning and Codex as the agent interface</strong>. ChatGPT and Claude appear here only as the broader LLM context, and Claude Code illustrates the coding-agent pattern. That connection raised the question behind the rest of the work: how much of the pattern survives when a wrong action changes the physical world?','论文的实现使用 <strong>OpenAI GPT-6 Astra 做多模态推理，并以 Codex 作为智能体接口</strong>。ChatGPT 与 Claude 在这里只说明 LLM 的背景，Claude Code 用来说明编程智能体的工作方式。由此产生了后面的问题：当一次错误动作会改变真实物理状态时，这套工作方式还能保留多少？')+'</div>'
    stages=[('01','Direct visual planning','直接从图像规划','We began by asking a multimodal agent to plan from robot-view images. It could interpret the goal, but the physical gaps remained: metric depth, collision-free motion, contact, high-rate control. That first attempt separated semantic competence from the robot-native competence a plan needs before it can run at all.','最初，我们让多模态智能体直接根据机器人视角图像做规划。它能理解目标，但物理层面的缺口依然存在：精确深度、无碰撞运动、接触、高频控制。这次尝试让语义理解与“让计划真正跑起来”的机器人能力，分成了两件事。'),('02','Tools and a return path for feedback','加入工具，并让物理反馈回到决策中','We then connected perception, grasping, planning, and control tools, and returned a fresh observation after each short execution. When the scene disagreed with the plan, the agent could revise its route. Structured memory made one trial worth more than its episode by keeping its conditions, outcome, and repair.','随后，我们接入感知、抓取、规划与控制工具，并在每次短段执行后返回新的观察。当场景与计划不一致时，智能体可以修改路线。结构化记忆保存了这次尝试的条件、结果与修复方式，让一次试错的价值超出它所在的回合。'),('03','Sparse teaching as a productive starting point','用少量示教提供有效起点','Tool use made zero-shot agent control feasible, yet learning one behavior by repeated trial still consumed interaction and model calls. Successful teaching supplies a subgoal sequence early, so exploration can concentrate on the variation, correction, and missing transitions the demonstrations do not cover. This became the Teach-and-Grow route.','工具调用使零样本智能体控制成为可行，但靠反复试错学会一个行为，仍然要消耗大量物理交互与模型调用。成功示教可以提前给出子目标序列，让探索集中在演示没有覆盖的变化、纠错与缺失环节上。这逐渐形成了 Teach-and-Grow 的路线。')]
    origins += '<div class="research-timeline">'
    for n,en,cn,body,bcn in stages:
        origins += f'<article><span class="timeline-index">{n}</span><div><h3>{t(en,cn)}</h3>{p(body,bcn)}</div></article>'
    origins += '</div><div class="research-note"><span lang="zh-CN">教学相长</span><p>'+t('Teaching gives exploration a starting structure. Execution exposes what the teaching left unresolved. Those gaps make the next teaching intervention more focused.','示教为探索提供初始结构，执行暴露示教尚未解决的问题，这些缺口又让下一次指导更有针对性。')+'</p></div><div class="reading-wide">'+p('Teaching reduced the search for a useful starting plan. The next question was what to keep from it: the record of one successful episode, or a behavior that could be grounded and executed in another scene?','示教缩小了寻找有效初始计划的范围。接下来的问题是：要从中保留什么——一次成功回合的记录，还是能够在别的场景里重新落实并执行的行为？')+'</div></div></section>'

    idea = '<section id="idea" class="section container">'+intro('03',t('THE CENTRAL IDEA','核心思路'),t('Make executable capability the object of learning.','把“可执行的能力”本身作为学习对象。'),t('A demonstration holds two different things: a strategy worth keeping, and physical details that belong to one scene. TGL separates them.','一次演示里其实有两样东西：值得保留的策略，以及只属于那个场景的物理细节。TGL 把它们分开。'))
    idea += '<div class="reading-grid"><div class="article-copy">'
    idea += p('Consider placing a bowl on a plate. Across demonstrations the hand may approach from different directions and follow different paths. The shared structure is steadier: acquire the requested bowl, establish that it is held, move toward the target relation, and release it onto the plate.','以“把碗放到盘子上”为例。不同演示里，接近方向与运动轨迹可以完全不同，但共同结构更稳定：拿到指定的碗，确认它被夹持，朝目标关系移动，再把它释放到盘子上。')
    idea += p('TGL represents one meaningful change as a <strong>Skill Block</strong>. The block keeps the goal, the reusable strategy, the conditions under which it applies, and the test of its outcome. The current observation supplies the actual object pose, grasp, path, and control target. Reuse therefore preserves the intended effect while the physical realization stays free to change.','TGL 用 <strong>Skill Block</strong> 表示一次有意义的状态变化。技能块保留目标、可复用策略、适用条件与效果判据；实际的物体姿态、抓取、路径和控制目标来自当前观察。复用时保留的是预期效果，物理实现则可以随场景改变。')
    idea += p('Training-free has a precise meaning here: acquiring the incoming task invokes no gradient update, no fine-tuning, and no reinforcement-learning stage. The agent and its specialist models may already be pretrained. What changes during acquisition is the explicit skill and memory state.','这里的 training-free 含义很明确：获取当前任务的过程不包含梯度更新、微调或强化学习阶段。智能体与专用模型可以已经是预训练好的；获取过程中改变的是显式的技能与记忆状态。')
    idea += '</div><div class="state-diagram"><div class="state-row"><span class="mono">θ</span><div><b>'+t('Pretrained model weights','预训练模型权重')+'</b><small>'+t('Fixed during task acquisition','任务获取过程中保持固定')+'</small></div><span class="state-label">FIXED</span></div><div class="state-row evolving"><span class="mono">B</span><div><b>Skill Library</b><small>'+t('Executable behaviors, scopes, and contracts','可执行行为、适用范围与契约')+'</small></div><span class="state-label">GROWS</span></div><div class="state-row evolving"><span class="mono">M</span><div><b>Experience Memory</b><small>'+t('Conditions, outcomes, diagnoses, and repairs','条件、结果、诊断与修复')+'</small></div><span class="state-label">GROWS</span></div><p>'+t('A task leaves the robot with something it can retrieve, inspect, and execute again.','完成任务后，机器人留下可以检索、检查和再次执行的能力。')+'</p></div></div>'
    idea += '<div class="invariant-strip"><div><span class="mono">RETAIN</span><h3>'+t('Semantic effects & strategy','语义效果与策略')+'</h3><p>'+t('What should change, in which order, under which conditions.','什么需要改变、先后顺序如何、适用于哪些条件。')+'</p></div><span class="strip-cross">×</span><div><span class="mono">RECOMPUTE</span><h3>'+t('Current physical realization','当前物理实现')+'</h3><p>'+t('Object bindings, grasp geometry, collision-free motion, and control.','物体绑定、抓取几何、无碰撞运动与具体控制。')+'</p></div></div><div class="reading-wide">'+p('The separation defines what has to be learned. Making it work on a robot adds a second connection: every retained subgoal has to lead to an action in the current scene, and every action has to return evidence that can change the next decision.','这种分离界定了“要学什么”。要让它在一台机器人上跑起来，还需另一层连接：每个保留下来的子目标都要能变成当前场景中的动作，而每个动作都要返回足以改变下一步决策的信息。')+'</div></section>'

    method = '<section id="method" class="section soft"><div class="container">'+intro('04',t('INSIDE THE ARCHITECTURE','架构内部'),t('Subgoal reasoning on top, geometric control underneath.','上层围绕子目标推理，下层完成几何与控制。'),t('The agent organizes the task at meaningful state transitions. Inside each block, specialized executors handle geometry and continuous control.','智能体在有意义的状态变化处组织任务；每个技能块内部，由专用执行器处理几何与连续控制。'))
    method += figure(2,t('Teaching, agentic execution, and persistent growth in TGL','TGL 的示教、智能体执行与持久积累'),t('One task moves through teaching, composition, execution, verification, and persistent storage. The resulting library and memory become the starting point for the next task.','一个任务经历示教、组合、执行、验证与持久化。形成的技能库与经验记忆成为下一个任务的起点。'))
    rows=[('A','Read demonstrations as evidence about change','把演示读成状态变化的证据','Demonstrations are cut at meaningful events, such as acquiring an object or establishing a containment relation. Segments align by what they accomplish, even when their timing and motion differ. The shared structure becomes a candidate strategy, and the variation across demonstrations decides how broadly it can be claimed: an example from one object stays narrow until more evidence supports a wider scope.','系统在“拿到物体”“形成容纳关系”这类有意义的事件处切开演示。片段按完成的效果对齐，即使时间与动作方式不同。共同结构成为候选策略，演示之间的差异决定这个策略可以被主张的范围有多大：只有单个物体的例子时，它就只适用于那个物体，除非有更多证据支持更宽的范围。'),('B','Give each skill a contract with the scene','让每个技能与当前场景建立明确契约','A block answers practical questions. What effect is intended? When does it apply? What evidence does it need? Which executors can realize it? How is success observed? What recovery is allowed? During acquisition, a closed gripper alone does not establish that the object is held; verification has to refer to the intended physical effect.','每个技能块要回答几个很实际的问题：期望什么效果？什么时候适用？需要什么证据？哪些执行器能实现？如何观察成功？允许什么恢复动作？以抓取为例，夹爪闭合并不足以说明物体已被夹住，验证必须指向预期的物理效果。'),('C','Revise the remaining plan after the robot acts','机器人动作后，再决定剩余计划','The working plan is an ordered composition of blocks, and its remainder can change. A passed effect opens the next stage; a failed or inconclusive effect can call for another observation, a different executor, or a revised route. This is where reasoning meets physical feedback: what happens next depends on what actually happened.','当前计划是一组有序的技能块，尚未执行的部分是可以改的。效果通过，进入下一阶段；效果失败或不确定，就可能需要再次观察、换一个执行器，或者修改路线。智能体的推理在这里与物理反馈相接：下一步取决于刚才真正发生了什么。'),('D','Validate before making a candidate reusable','验证通过后，候选行为才进入复用流程','A promising candidate is evaluated beyond its teaching demonstrations. Supported scope, executor compatibility, outcome test, and recovery are checked before it enters the library; weak candidates get narrowed or repaired. Library growth is therefore a decision about one behavior and the conditions under which it works, not an automatic consequence of every episode.','有希望的候选行为要在示教之外的场景中评估。支持范围、执行器兼容性、效果判据与恢复方式都要先检查，通过后才进入技能库；不够可靠的候选会被缩小范围或修复。技能库的增长因此是对“一个行为及其生效条件”的一次明确判断，而不是每个回合自动累积的结果。')]
    method += '<div class="method-narrative">'
    for n,en,cn,body,bcn in rows:
        method += f'<article><span class="mono method-letter">{n}</span><div><h3>{t(en,cn)}</h3>{p(body,bcn)}</div></article>'
    method += '</div>'+figure(3,t('Fields and runtime loop of a Skill Block','Skill Block 的字段与运行时闭环'),t('The contract connects a semantic subgoal to grounded execution and observable evidence.','技能契约连接语义子目标、落实到当前场景的执行，以及可观察的结果证据。'))
    method += '<div class="walkthrough"><div class="walkthrough-heading"><span class="eyebrow">'+t('A WORKED CONCEPTUAL EXAMPLE','一个贯穿方法的概念示例')+'</span><h3>'+t('“Put the bowl on the plate.”','“把碗放到盘子上。”')+'</h3><p>'+t('Follow which information is retained and which decisions are made again.','看看哪些信息被保留，哪些决策需要根据当前场景重新做出。')+'</p></div><div class="walk-tabs" role="group" aria-label="'+t('Explore the execution stages','查看执行阶段')+'" hidden>'
    steps=[('teach','Read the teaching','理解示教','Acquire → transport → release','获取 → 搬运 → 释放','The demonstrations supply the subgoals and their order. They also show which conditions are worth checking, such as holding the bowl before transport starts. Their original pixel coordinates and exact trajectory are not part of the reusable strategy.','演示提供子目标与顺序，也揭示需要检查的条件，例如搬运前应保持对碗的夹持。原始像素坐标和精确轨迹不属于可复用策略。'),('ground','Ground the block','落实到当前场景','Current bowl → feasible grasp','当前目标碗 → 可行抓取','The block binds the requested object to the current observation, and a compatible grasping and motion backend computes the action. The contact point can differ from the teacher’s while the state the block is after stays the same.','技能块将任务中的目标物体绑定到当前观察，由兼容的抓取和运动后端计算具体动作。接触位置可以与教师不同，但希望达到的“已获得物体”状态保持一致。'),('verify','Read the outcome','读取动作结果','Effect → continue / reobserve / repair','物理效果 → 继续／再观察／修复','After execution, a verifier checks whether the bowl is actually held. A weak or failed grasp changes the next decision: the agent can look again, or revise the remaining route before it attempts placement.','执行后，验证器检查碗是否确实被夹持。不牢固或失败的抓取会改变下一步决策，智能体可以再次观察，或在放置前修改剩余路线。'),('retain','Keep the lesson','保留可复用经验','Validated behavior + useful context','已验证行为 + 有用的条件信息','The executable strategy and its scope enter the Skill Library once validated. The conditions of the attempt, its outcome, and a useful repair enter Experience Memory. A later task can retrieve both.','通过验证的可执行策略及其范围进入技能库。这次尝试的条件、结果和有用的修复方式进入经验记忆，后续任务可以同时检索两者。')]
    for i,(key,en,cn,*_) in enumerate(steps):method += f'<button data-stage="{key}" aria-pressed="{str(i==0).lower()}"><span>0{i+1}</span>{t(en,cn)}</button>'
    method += '</div>'
    for key,en,cn,state,scn,body,bcn in steps:
        method += f'<article class="walk-panel" id="stage-{key}"><span class="mono">{t(en,cn)}</span><h4>{t(state,scn)}</h4>{p(body,bcn)}</article>'
    method += '</div><p class="implementation-note">'+t('In the paper’s current system, OpenAI GPT-6 Astra and Codex provide task-level reasoning and tool interaction. Detection, segmentation, RGB-D geometry, Contact-GraspNet, MPLib, and controllers supply the physical grounding and execution.','论文当前系统使用 OpenAI GPT-6 Astra 和 Codex 进行任务级推理与工具交互。检测、分割、RGB-D 几何、Contact-GraspNet、MPLib 与控制器负责物理场景落地和执行。')+'</p></div></section>'

    memory='<section id="memory" class="section container">'+intro('05',t('WHAT THE ROBOT KEEPS','机器人留下了什么'),t('A skill stores behavior. Memory stores its lessons.','技能保存行为，记忆保存使用它的经验。'),t('Solving one episode and acquiring a lasting capability are different events. TGL keeps the two objects separate.','完成一次任务与获得持久能力，是两件事。TGL 把需要保留的两类对象分开。'))
    memory+='<div class="memory-columns"><article><span class="mono">B / EXECUTABLE</span><h3>Skill Library</h3>'+p('The library holds behaviors that can be selected and run: their subgoals, supported conditions, grounding rules, compatible tools, and verification logic. A text description of “how to grasp” is not enough. The block has to connect that intent to an executor and to a test of its effect.','技能库保存能够被选择并运行的行为：子目标、适用条件、场景落实规则、兼容工具与验证逻辑。单有一句“如何抓取”的描述并不够，技能块还必须把意图接到执行器，以及一个能检验效果的判据上。')+'</article><article><span class="mono">M / CONTEXTUAL</span><h3>Experience Memory</h3>'+p('Memory keeps the context of use: the task, the blocks that were selected, the observations, the outcome, the diagnosis, the repair. A failed attempt may reveal an unsuitable grasp family or an ambiguous observation, and keeping that explanation can guide the next selection without turning every episode into a new executable block.','经验记忆保存的是使用情境：任务、选中的技能块、观察、结果、诊断与修复。一次失败可能暴露出不合适的抓取方式，或一次含糊的观察；把这些解释保留下来，就能指导下一次选择，而不必把每个回合都变成新的可执行技能。')+'</article></div><div class="reading-wide">'
    memory+=p('The separation also keeps the system inspectable. A person can narrow an overgeneralized scope, change a recovery rule, or mark a tool version as incompatible. Keeping a file is not the same as keeping a behavior: the right block still has to be retrieved, grounded in current sensing, and executed successfully, and those remain separate questions for a robot that learns over years.','这种分离也让系统保持可检查。人可以收窄过宽的范围、修改恢复规则，或把某个工具版本标为不兼容。保存了文件，不等于保留了行为能力：系统仍然要检索到正确的技能块、把它落实到当前传感信息上，并成功执行——对一个长期学习的机器人来说，这是几个分别需要回答的问题。')+'</div><div class="reading-wide">'+p('The paired videos below show the loop directly. Start from the teacher’s task structure, then watch how TGL reaches the same outcome through a different grasp, or what it does when the first attempt fails to secure the object.','下面的对照视频把这个过程直接呈现出来：先看教师给出的任务结构，再看 TGL 如何用不同的抓取达到同样的结果，以及第一次没能夹稳物体时它会怎么做。')+'</div></section>'

    investigation='<section id="results" class="section soft"><div class="container">'+intro('07',t('WHAT WE INVESTIGATED','我们研究了什么'),t('Four studies of how the mechanism behaves.','四项研究，考察机制本身的行为。'),t('The videos show single scenes. The studies look behind them: where a skill comes from, what survives a task, and what changes the next execution.','视频展示的是单个场景。研究看的则是场景背后：技能从哪里来、一次任务结束后留下什么、什么因素改变了下一次执行。'))
    studies=[('Demonstration → semantic effects','从演示到语义效果','Ten saved demonstrations from two related LIBERO-Object tasks are split into 40 predicted stages. Ordered role/type accuracy is 1.000, and all 20 observable acquire/release effects are confirmed. Frame boundaries are much weaker: exact-frame F1 is 0.10, rising to 0.90 within two sampled frames. The study is deliberately narrow, using deterministic visual cues and typed rules to isolate the representation and verification mechanism, and it separates two things cleanly. The stage sequence is recovered; the exact frame is not.','来自两个相关 LIBERO-Object 任务的十段演示被切分为 40 个预测阶段。有序角色/类型准确率为 1.000，20 个可观察的获取与释放效果全部得到确认。帧边界的表现要弱得多：精确帧 F1 为 0.10，放宽到两个采样帧之内为 0.90。这项研究有意限定在确定性视觉线索与类型化规则上，用来单独考察表示与验证机制，它清楚地分开了两件事：阶段顺序可以恢复，精确帧位置不能。'),('Candidate → persistent Skill Block','从候选行为到持久技能','Three teacher trajectories produce two blocks: acquire the requested object, release it in the required relation. On separated states the pair succeeds 3/3, and it still succeeds 3/3 after save-and-reload. On farther states 6–8, the route stops at the first missing semantic effect, which is what keeps a local mistake from propagating through the task.','三条教师轨迹产生两个技能块：获取指定物体，按所需关系释放。在分离的评估状态上成功率 3/3，保存并重载后仍然是 3/3。在更远的 6–8 号状态上，路线会停在第一个缺失的语义效果处——正是这一点阻止了局部错误在任务中继续传播。'),('Physical feedback → a revised decision','从物理反馈到修正决策','Online traces inspect two decisions: replanning the remaining route in a bowl-placement task, and requesting another observation when the drawer-opening verification comes back inconclusive. A separate failure cohort locates where the remaining attempts broke: two before motion planning, four in path consistency or calibration, two at gripper closure.','在线轨迹考察了两类决策：在碗放置任务中重规划剩余路线，以及在开抽屉任务的验证结果不确定时再看一次。另一组失败试验进一步定位了剩余尝试的问题所在：两次发生在运动规划之前，四次与路径一致性或标定有关，两次出现在夹爪闭合环节。'),('Library growth → related-task reuse','从技能库扩充到相关任务复用','One controlled pilot holds executor, seeds, and budget fixed, and adds only the learned acquisition and release blocks. Related-task success changes only once those two blocks enter the library, with the executor and the evaluation conditions untouched. The sample is small, so the paper reports it as a directional observation rather than a benchmark claim.','一项受控试验固定执行器、随机种子与预算，只增加学得的获取与释放技能块。相关任务的成功情况，是在这两个技能块入库之后才发生变化的，而执行器与评估条件始终未变。样本很小，因此论文把它记为方向性观察，而不是基准结论。')]
    investigation+='<div class="study-narrative">'
    for en,cn,body,bcn in studies:investigation+='<article><h3>'+t(en,cn)+'</h3>'+p(body,bcn)+'</article>'
    investigation+='</div><div class="paper-callout"><p>'+t('Experimental protocols, quantitative results, and comparison tables are available in the paper.','实验协议、定量结果和方法对比表请参阅论文。')+f'</p><a href="{paper}#page=4">'+t('Read the evaluation','阅读实验部分')+' ↗</a></div></div></section>'

    growth='<section id="growth" class="section container">'+intro('08',t('THE LARGER RESEARCH DIRECTION','更长远的研究方向'),t('Scale the experience a robot can actually reuse.','让机器人真正能够复用的经验持续增长。'),t('These studies follow the path from a taught task to a reusable skill. The next question concerns a longer timescale: what happens as that process repeats throughout a robot’s working life?','这些研究跟踪了从示教任务到可复用技能的过程。下一个问题涉及更长的时间尺度：当这个过程在机器人的整个工作周期中反复发生时，会带来什么变化？'))
    growth+='<div class="reading-wide">'+p('More stored trajectories do not necessarily mean more capability. Experience is useful only if it can still be retrieved, grounded, and composed for a new scene. The Teach-and-Grow hypothesis relates this effective reusable experience to declining future-task error and teaching demand. It is a hypothesis about lifelong capability growth, and the present experiments do not yet fit a universal scaling law.','存储更多轨迹并不必然带来更多能力。只有能够在新场景中被检索、落实和组合的经验，才具有复用价值。Teach-and-Grow 假设将这种有效可复用经验与未来任务误差、示教需求的下降联系起来。它讨论的是终身能力积累，而当前实验还没有拟合出普适缩放定律。')+'</div>'
    growth+=figure(4,t('Teach-and-Grow scaling hypothesis and future fast-policy path','Teach-and-Grow 缩放假设与未来快速策略路径'),t('Conceptual predictions: more reusable experience can reduce future error and the teaching required for related tasks. The curves are schematic.','概念性预测：可复用经验的积累，有望降低未来任务误差和相关任务的示教需求。曲线为示意。'))
    growth+='<div class="reading-wide subtopic"><h3>'+t('Acquire unfamiliar behavior deliberately; execute familiar behavior efficiently.','对陌生行为进行细致获取，让熟悉行为高效执行。')+'</h3>'+p('Agentic acquisition uses repeated observation, reasoning, and tool calls. That deliberation is useful at the frontier of the robot’s knowledge, but it is more expensive than feed-forward policy inference. The proposed slow-teacher/fast-student path assigns the agent to novelty and diagnosis, while a learned policy handles mature behavior. Verified trajectories could later train that student; distillation is a proposed extension of the current work.','智能体获取行为时需要反复观察、推理与调用工具。这种细致处理适合机器人尚不熟悉的任务，但成本高于前馈策略推理。因此，拟议的“慢教师–快学生”路线让智能体处理陌生任务与诊断，让学习策略执行成熟行为。未来可以用经过验证的轨迹训练学生策略；蒸馏是本工作的扩展方向。')+'</div>'
    growth+='<div class="reading-wide subtopic"><h3>'+t('VLA, WAM, and classical robotics remain part of the system.','VLA、WAM 与经典机器人方法都可以进入这一系统。')+'</h3>'+p('A learned policy can implement a block, execute a familiar composition, or become a future student. A geometric planner can bridge two skills; a visual servo can close a local loop; tactile sensing can strengthen a contact check. TGL supplies the semantic contract and feedback structure through which these components contribute to a task.','学习策略可以实现某个技能块、执行熟悉的技能组合，或成为未来的学生。几何规划器可以连接两个技能，视觉伺服可以完成局部闭环，触觉可以加强接触检查。TGL 提供语义契约与反馈结构，让这些组件共同服务于任务。')+p('The same perspective extends to teaching sources. Robot trajectories, simulation, human video, and written procedures offer different kinds of evidence. A manual may reveal the order of operations while leaving the grasp unresolved. The architecture preserves that distinction: semantic knowledge guides acquisition, and robot-specific grounding and validation determine what can actually run.','同样的思路也适用于示教来源。机器人轨迹、仿真、人类视频与书面操作流程提供不同类型的证据。手册可能揭示操作顺序，却没有解决抓取方式。架构保留这种区别：语义知识指导获取，机器人相关的场景落地与验证决定哪些行为真正能够运行。')+'</div>'
    growth+=figure(6,t('Models, tools, teaching sources, and feedback in the TGL ecosystem','TGL 生态中的模型、工具、示教来源与反馈'),t('A whole-system view. Dashed paths mark proposed distillation and fleet sharing.','系统整体视角。虚线路径表示拟议的蒸馏与多机器人共享。'))
    growth+='<div class="deep-dive"><h3>'+t('Why local skill updates may change acquisition cost','为什么局部技能更新可能改变能力获取成本')+'</h3><div class="reading-wide">'+p('A local skill addition can avoid reopening every part of the learning system, provided grounding, validation, compatibility, and retrieval remain manageable. Those conditions matter: unrestricted pairwise compatibility checks can make library growth expensive. The paper analyzes these different cost regimes rather than treating low-cost growth as automatic.','如果场景落地、验证、兼容性检查和检索成本保持可控，局部增加技能就可能避免重新更新整个学习系统。这些条件至关重要：不受限制的两两兼容性检查同样可能使技能库增长变得昂贵。论文分析不同的成本情形，而不把低成本增长视为自动成立。')+'</div>'+figure(5,t('Conditional acquisition-cost regimes','条件性的能力获取成本模型'),t('Analytic cost regimes under different assumptions about coverage and local compatibility.','在不同覆盖需求与局部兼容性假设下的分析性成本情形。'))+'</div></section>'
    abstract='<section id="abstract" class="section soft"><div class="container">'+intro(t('ABSTRACT','摘要'),t('PAPER SUMMARY','论文摘要'),t('The paper in its own words.','论文摘要原文。'),t('The abstract of the technical report, reproduced verbatim so the claims can be quoted and checked directly.','技术报告摘要原文，便于直接引用与核对。'))
    abstract+='<blockquote class="abstract-text">'+t(seo.get('abstract',''),seo.get('abstract_zh',''))+'</blockquote>'
    abstract+='<p class="paper-keywords"><span class="kw-label">'+t('Keywords','关键词')+'</span>'+t(' · '.join(seo.get('paper_keywords',[])),' · '.join(seo.get('paper_keywords_zh',[])))+'</p>'
    abstract+='<div class="reading-wide"><h3>'+t('Where this work sits','这项工作处在什么位置')+'</h3>'+p(seo.get('context',''),seo.get('context_zh',''))+'</div>'
    abstract+='<div class="abstract-meta"><p>'+t('Technical report · Shanghai Jiao Tong University · 2026','技术报告 · 上海交通大学 · 2026')+'</p><p class="small">'+t('Cite as: Chang Nie, Zhe Liu and Hesheng Wang, “Teach and Grow: An Agent-Centered Architecture for General Robot Learning,” technical report, Shanghai Jiao Tong University, 2026.','引用格式：Chang Nie, Zhe Liu and Hesheng Wang, “Teach and Grow: An Agent-Centered Architecture for General Robot Learning,” 技术报告，上海交通大学，2026。')+'</p></div></div></section>'

    glossary='<section id="glossary" class="section container">'+intro(t('GLOSSARY','术语表'),t('KEY TERMS','关键术语'),t('The terminology this work introduces.','本工作提出的术语。'),t('Each term is defined on its own so that it can be quoted, checked, or reused without the surrounding page.','每条定义都保持自包含，便于单独引用、核对或复用。'))
    glossary+='<dl class="glossary-grid">'
    for _term in terms:
        glossary+='<div class="glossary-item"><dt>'+t(_term['name'],_term.get('name_zh',_term['name']))+'</dt><dd>'+t(_term['definition'],_term.get('definition_zh',_term['definition']))+'</dd></div>'
    glossary+='</dl></section>'

    faq='<section id="faq" class="section soft"><div class="container">'+intro(t('FAQ','常见问题'),t('QUESTIONS','问答'),t('Direct answers about TGL.','关于 TGL 的直接回答。'),t('Short, self-contained answers written so that a reader or an AI assistant can quote them without the rest of the page.','以下回答刻意写成自包含的，读者或 AI 助手可以直接引用，而无需依赖页面其余部分。'))
    faq+='<div class="faq-list">'
    for _item in seo.get('faq',[]):
        faq+='<article class="faq-item"><h3>'+t(_item['q'],_item.get('q_zh',_item['q']))+'</h3><div class="faq-answer">'+p(_item['a'],_item.get('a_zh',_item['a']))+'</div></article>'
    faq+='</div></div></section>'

    return dict(overview=overview,origins=origins,idea=idea,method=method,memory=memory,investigation=investigation,growth=growth,abstract=abstract,glossary=glossary,faq=faq)
